### PR TITLE
Feature/54 added option to cap the creation of log events based on governor limits

### PR DESCRIPTION
**Pull request by j-fischer**
Added Global Config record to limit the amount of Platform Events that RFLIB will publish during a transaction

### CODE REVIEW

**Comment by deniskrizanovic** [comment]
What about publishing a final event in the table that says "logging limit exceeded" .. Switching to systemdebug isn't as observable.

**Comment by j-fischer** [comment]
> What about publishing a final event in the table that says "logging limit exceeded" .. Switching to systemdebug isn't as observable.

Great idea! This got me thinking. I can think of two options here. 
1) Add an extra event when the limit is at (Publishing Limit - 1) that indicates the end of the log events as you suggested. 
2) Extended the Log Event object to have a "Platform_Details__c" field, which is of type Text(255) and optional. This could contain a string like: rflibEvent=2, publishImmidiateDML=4, publishingLimit=10; cpuTime=1234

I am really tempted about option 2 because I think I could add more limit information to every event and that could be super useful. Not sure about the format yet, though. 

Also, I am second guessing my choice to validate based on `Limits.getPublishImmediateDML()`, but use an internal counter instead. That way there is no risk for the counter to jump multiple steps. 

@deniskrizanovic What are your thoughts?

**Comment by deniskrizanovic** [comment]
Hi Johannes,

My perspective is that the logging framework should be as cognitively
simple as possible. Adding "cognitive complexity" to the framework with an
extra column, that sometimes is filled is too much.

Think about log4j.. Essentially, a developer could use the framework for 20
years and never know there was more to it than the debug/error methods..

Regarding, using an internal counter. You can't actually do that. Other
processes are consuming the Event Limit too, so you need to be aware of the
context you're operating in.

regards,
denis-

**Comment by j-fischer** [comment]
Hi @deniskrizanovic ,

I totally agree with you about the simplicity of the of the contract  (interface) and I am sure you noticed how much of an influence log4j had on the library. But I feel there may have been a misunderstanding: I was not planning to extend the log methods (debug(), info(), etc) to include a new parameter. I simply want to add a new field to the Log Event where I can store some environment/platform details. For example in Apex, when dealing with a CPU limit reach issue, it would be great to understand how much time is spent between different log statements, especially when INFO is the Log Reporting Level. In the frontend, it would be great if the browser version was automatically collect, and on the functions side, information about the process. 
The framework will take care of it behind the scenes and nothing will have to change on the consumer side. I will open a new feature request for this because I could use this feature myself. Please feel free to comment on the ticket there. 

Now, regarding this PR: 
>Regarding, using an internal counter. You can't actually do that. Other processes are consuming the Event Limit too, so you need to be aware of the context you're operating in.

Actually, I have to use the internal counter for exactly the reason that you mentioned. If I am not in control of the counter then I cannot implement the logic that you asked for as other, non-logging platform events could move the Limit way beyond the configured threshold without RFLIB ever detecting that it was reached. 

When you set the global value to 50, that means RFLIB will publish up to 50 events, unless the overall Governor limit is reached earlier. To your point, though, I added another if statement to guard against exceeding the Governor Limit. 

Your feedback certainly pointed out some flaws in the the initial implementation when I opened the PR. I believe I've got all of those addressed now and it is the final version. I opted to embed a message to the top of the last Log Event instead of sending a separate event so that the log information of the last event isn't lost. 

I hope this implementation will work for you. Thanks again for the feedback. 

Cheers

**Pull request merged**
